version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: badminton-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass ""
    restart: unless-stopped
    networks:
      - badminton-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: badminton-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - badminton-network
    restart: unless-stopped

volumes:
  redis-data:
    driver: local

networks:
  badminton-network:
    driver: bridge