version: '3.9'
services:
  redis:
    image: redis:7-alpine
    container_name: badminton-redis
    ports: ["6379:6379"]
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped

  backend:
    image: ghcr.io/your-org/badminton-backend:0.1.0 # 替换为你的镜像地址/版本
    container_name: badminton-backend
    depends_on: [redis]
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET:-please-reset-32-bytes}
      SPRING_PROFILES_ACTIVE: docker
    ports: ["8080:8080"]
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: badminton-nginx
    depends_on: [backend]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../frontend-admin/dist:/usr/share/nginx/html/admin:ro
      - ../../frontend-h5/dist:/usr/share/nginx/html/h5:ro
    ports: ["80:80"]
    restart: unless-stopped

volumes:
  redis-data:
    driver: local

