spring:
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 2
          max-wait: 5s

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  metrics:
    enable:
      jvm: true
      process: true

jwt:
  secret: badminton-secret
  expireMinutes: 43200
