# SpringBoot 主配置文件
# 作者: xiaolei

spring:
  application:
    name: badminton-backend
  profiles:
    active: local

# 服务器配置
server:
  port: 8080

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  metrics:
    enable:
      jvm: true
      process: true

# JWT配置
jwt:
  # 注意：HMAC-SHA(HS256/384/512)密钥长度需>=256 bits(32字节)
  # 默认提供安全长度示例，请在生产环境使用更安全的随机密钥
  secret: badminton-secret-please-change-to-32bytes-or-longer-2025
  expireMinutes: 43200

# CORS配置
app:
  security:
    cors:
      allowed-origins: "*"

# Swagger配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tryItOutEnabled: true
    operationsSorter: alpha
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs

# 日志配置
logging:
  level:
    cn.badminton: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE